name: 'Frontend: PR'

on:
  pull_request:
    branches: ['*']

jobs:
  configured:
    uses: valitydev/action-frontend/.github/workflows/configured.yml@v0.1
  check:
    name: Check
    runs-on: ubuntu-latest
    needs: exists
    if: needs.configured.outputs.exists == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: valitydev/action-frontend/setup@v0.1
      - uses: valitydev/action-setup-thrift@v1.0.0
      - run: npm ci
      - name: Codegen
        run: npm run codegen
